### ISSUE TITLE
OpenWebif new Design

### ISSUE THREAD

**Issue by rubix86** [BlackHole/obh-core#6]
hey why when I try to activate openwebif new design by browser
![39727502-3a63a8ac-5253-11e8-9827-cba5b1459e23](https://user-images.githubusercontent.com/17280907/40058475-85c7d616-5851-11e8-9dc2-1120019c59db.PNG)
I got this result 
![39971733-a3620f22-5700-11e8-9be6-9c98812bcb27](https://user-images.githubusercontent.com/17280907/40058519-a54acf98-5851-11e8-9564-b0217ce16319.PNG)
can you fix it. other oe-alliance images like OpenATV work like a charm

**Comment by nunigaia** [comment]
There´s "none" software issue.

On terminal install the following package, by running the following commands:

1) **opkg install enigma2-plugin-extensions-openwebif-themes**

2) **reboot**

After that, apply the new design.

best regards
nunigaia
